name: Send Telegram Message

on:
  workflow_dispatch: # You can also use push or other events

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Run Telegram script
        env:
          TELE_API: ${{ secrets.TELE_API }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: node sendTelegram.js
