name: Run JS with Secrets

on:
  push:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # Get your repo

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Run JS script with secrets
        env:
          TELE_API: ${{ secrets.TELE_API }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: node script.js
